### ISSUE TITLE
readme says wrong variable name

### ISSUE THREAD

**Issue by art0007i** [RileyGuy/FourierForge#1]
in the readme it says the variables are called '`StreamFFTValue(number)`' while they are ACTUALLY called '`FFTStreamValue(number)`'

**Comment by BlueCyro** [comment]
Thanks, I'll fix this right away.

**Comment by BlueCyro** [comment]
Also just for posterity since I didn't mention it - fixed in [dc74218](https://github.com/RileyGuy/FourierForge/commit/dc7421874a333b201c484eedaa760e3ded13f09c)
